server:
  port: 8080
  
spring:
  cloud:
    gateway:
      routes:
        - id: catalogRoute #Identificando la ruta del service de producto
          uri: http://localhost:8082/ #URL donde se hará el redirect segun el predicate definido
          predicates: #RReglas de análisis de una request
            - Path=/catalog/**
        - id: movieRoute #Identificando la ruta del service de producto
          uri: http://localhost:8084/ #URL donde se hará el redirect segun el predicate definido
          predicates: #RReglas de análisis de una request
            - Path=/movies/**
        - id: serieRoute #Identificando la ruta del service de producto
          uri: http://localhost:8080/ #URL donde se hará el redirect segun el predicate definido
          predicates: #RReglas de análisis de una request
            - Path=/serie/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
